### ISSUE TITLE
About IOU of different models

### ISSUE THREAD

**Issue by txytju** [AntiAegis/Human-Segmentation-PyTorch#2]
Thanks for your great work!
In the table at the bottom of readme, results of different models are showed, and I've noticed that Unet-Mobilenet get the best iou rather than models that have much more parameters. What do you think have caused this? Thanks!

**Comment by AntiAegis** [comment]
Hi @txytju,
In my opinion, training data is quite small (5~6k), therefore, having larger networks does not mean having higher mIoU.
