### ISSUE TITLE
models.backbonds.EfficientNet is not a package

### ISSUE THREAD

**Issue by l1346792580123** [AntiAegis/Human-Segmentation-PyTorch#6]
![8949002d27614f4d92be657b311ab04](https://user-images.githubusercontent.com/25956606/62865969-61ee2900-bd42-11e9-9033-b3778badef1a.png)

![6e986aa3f1abc5b52282b3b2bd7f6b5](https://user-images.githubusercontent.com/25956606/62865916-41be6a00-bd42-11e9-9dd9-ae3e4ea25e3d.png)

**Comment by NguyenDangBinh** [comment]
dear,
I got the same error!

**Comment by AntiAegis** [comment]
I fixed the error
